
about :

  name : "wTraverser"
  description : "Collection of routines to traverse data structures, no matter how compex and cycled them are. Traverser may be used to inspect data, make some transformation or duplication. Traverser relies on class relations definition for traversing. Use the module to traverse your data."
  version : "0.3.64"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest staging
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/wTraverser.git
  bugs : https://github.com/Wandalen/wTraverser/issues

step :

  export.proto :
    inherit : predefined.export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

